### ISSUE TITLE
Unified media handling

### ISSUE THREAD

**Issue by eyelidlessness** [enketo/enketo#990]
In enketo/enketo-express#459 I discussed some future steps we could take to further simplify media URL logic. This issue will be used to track those changes. Depending on the size, and coherent overlap of the work described here, I may submit a single PR, or break it into smaller chunks.

## Tasks

- [ ] **Generate media URLs client-side:** there's little remaining barrier to moving media URL parameterization to the client. Besides reducing unnecessary scope of the server's responsibilities, it will also unblock some of the other changes discussed in the first PR.

- [ ] **Offline-capable requests for media:** currently these requests are handled by replacing `src` attributes with `data-offline-src`, with an additional step to look those up and initiate media loading each time a form/instance is loaded, when a form is reset, when repeat instances are added, and so on. This distinction can be eliminated, instead handling those requests in `fetch` events within the Service Worker. We may also be able to handle caching at that level rather than in IndexedDB, but I'll likely split that off as a separate work item and defer it for another future follow-up.

- [ ] **Consistent handling of media URL resolution and requests:** there are several different ways URLs are resolved, depending on their type/role in the form: binary defaults, media in labels, external secondary instances, last-saved, instance attachments. I plan to unify these so that there is one consistent way that all media URLs are resolved and requested/fulfilled.

It may be tempting to combine these last two tasks, as a Service Worker is capable of handling both and it would enable even further simplification. Unfortunately, Service Workers cannot run in some browsers' private/incognito modes. While this is already a restriction of offline-capable mode, it's not a reasonable limitation for online-only, edit or preview modes. In any case, consistent handling of URL resolution can be shared, and hopefully the offline portion will just be a small wrapper around that specific to the pertinent Service Worker APIs.
